Corrected dependency in Linux build documentation
opennox/opennox pull request #623
Opened 2023-08-30 19:51 UTC by XandrosDarkstorm

## Required sign-off

- [x] I confirm that my PR does not contain any commercial or protected assets and/or source code.
- [x] I agree in advance that my codes will be licensed automatically under the Apache License or similar BSD/MIT-like
      open source licenses in case if OpenNox Project will adopt such a non-GPL license in the future.

## PR explanation

This PR changes `gcc` requirement to `gcc-multilib`. Without installing gcc-multilib, gcc cannot compile 32 bit code at all.

2023-08-30 20:29 UTC, Evengard approved these changes

2023-08-30 21:24 UTC, dennwc requested changes

2023-08-30 21:24 UTC, dennwc commented on docs/build-linux.md
> +sudo apt install golang
Debian is lagging behind pretty heavily in terms of Go versions.

Because of this, I don't want to recommend or support this install option at all. It happened that we still support 1.19, but I was preparing libs to bump version to 1.20 recently.

So it's better to install via official archives or Snap. Or find some ppa with more recent version.

As a general rule, we support two latest Go releases, which are currently 1.20 and 1.21.

2023-08-30 21:30 UTC, XandrosDarkstorm commented on docs/build-linux.md
> +sudo apt install golang
First of all it depends on Debian you use. Testing release is definitely not lagging behind too much and sid is usually up-to-date.
That is not the point. The point is -- we have to specify the lowest supported version of Go and if user has it on repositories, they must be able to use it regardless of repository.

2023-08-30 21:32 UTC, XandrosDarkstorm commented on docs/build-linux.md
> +sudo apt install golang
But i agree -- i should change the text to something neutral.

2023-08-31 06:12 UTC, dennwc approved these changes

2023-08-31 06:13 UTC, merged