Migrate 3 pointer usages
opennox/opennox pull request #704
Opened 2024-06-27 04:28 UTC by blmarket

Seems like these 3 pointers are for 3 volumes in option screen (music, dialog, fx volume). As the pointer always points to the same location, it's safe to replace them with memmap methods.

## Testing

Just played game for 1 hour without breaking

## Required sign-off

- [x] I confirm that my PR does not contain any commercial or protected assets and/or source code.
- [x] I agree in advance that my codes will be licensed automatically under the Apache License or similar BSD/MIT-like
      open source licenses in case if OpenNox Project will adopt such a non-GPL license in the future.

2024-06-27 09:41 UTC, dennwc requested changes
We are kind of trying to do the opposite - extract all variables from that opaque data blob that `memmap` accesses :sweat_smile:

2024-06-27 13:55 UTC, blmarket commented
> We are kind of trying to do the opposite - extract all variables from that opaque data blob that `memmap` accesses 😅

I think I see your point. Let me add another conversion to replace those memmap accesses as well.

2024-06-28 11:56 UTC, dennwc commented on src/legacy/vardefs.go
> +	counter_5d4594_830876  *TimerGroup = &TimerGroup{}
Ideally _everything_ we pass to C should be allocated on C heap to prevent possible memory corruption from C. So here, `alloc.New` should be used.

2024-06-28 11:56 UTC, dennwc commented on src/legacy/GAME2.c
> +			v2[29] = dword_587000_127004;
Should it be `&dword_587000_127004`?

2024-06-28 11:56 UTC, dennwc commented on src/legacy/GAME2.c
> +	sub_486520(*(unsigned int**)&dword_587000_127004);
I don't understand why this variable changed. The offset is completely different here :thinking:

2024-06-28 11:56 UTC, dennwc commented on src/legacy/vardefs.go
> +func get_counter_5d4594_830876() unsafe.Pointer {
`get_counter_5d4594_830876` -> `get_counter_5d4594_830876_ptr`
Same for others.

2024-06-28 11:56 UTC, dennwc commented on src/legacy/dialog.go
> +	TimerSetParams(&counter_5d4594_830876.Timers[0], 0x1F4 /* 500 */, 0x4000)
```suggestion
	TimerSetParams(&counter_5d4594_830876.Timers[0], 500, 0x4000)
```

2024-06-29 00:30 UTC, blmarket commented on src/legacy/GAME2.c
> +			v2[29] = dword_587000_127004;
My bad when cleaning up PR. dword_587000_127004 is a pointer to (0x5d4594, 1045324), and can be replaced to get_counter_5d4594_1045324() instead.

2024-06-29 00:32 UTC, blmarket commented on src/legacy/GAME2.c
> +	sub_486520(*(unsigned int**)&dword_587000_127004);
Ditto with above comment. But logically it's still true - dword_587000_127004 is always a pointer to (0x5d4594, 1045324).

2024-06-29 16:20 UTC, blmarket commented
Seems this PR made a regression - in the option menu, changing the dialog volume will play a sample voice, but somehow this one made it muted (or not played at all)

I feel it's too early to move those memmap... Let me try in different way.

2024-06-29 16:20 UTC, closed without merging