Separate timer and dialog package out from legacy
opennox/opennox pull request #706
Opened 2024-07-04 04:36 UTC by blmarket

Hey, I'm not sure this PR aligns with overall direction you may want, so
just created this PR to explain what I think. Feel free to give your
opinion on it.

Motivation: Encapsulate dialog package so we can have unit test and
integration test available for dialog package without initiating whole
legacy package.

Next steps:

- Remove all memmap usages in dialog package
- Make sure Dialog member fields are never accessed outside of the
  package
- Instantiate Dialog instance

## Required sign-off

- [ ] I confirm that my PR does not contain any commercial or protected assets and/or source code.
- [ ] I agree in advance that my codes will be licensed automatically under the Apache License or similar BSD/MIT-like
      open source licenses in case if OpenNox Project will adopt such a non-GPL license in the future.

2024-07-04 04:38 UTC, blmarket commented on src/legacy/dialog/dialog.go
> +
XXX: Could not manage to use common library (somehow import broken)

2024-07-04 10:32 UTC, dennwc requested changes

2024-07-04 10:32 UTC, dennwc commented on src/legacy/timer/timer.go
> +#include "../GAME2_2.h"
This won't work, unfortunately.

Go has a very particular way of handling C build process. C files and headers _must_ be in the same directory. Sub-folders or parent folders won't work - it will just stop recognizing changes to these C files.

This is why we only start moving things to packages when they are completely clean from any C types.

2024-07-04 10:33 UTC, dennwc commented on src/legacy/dialog/dialog.go
> +
Circular dependency, I guess? Or maybe its not exported (name start from lower-case).

2024-07-04 23:28 UTC, blmarket commented on src/legacy/dialog/dialog.go
> +
Hope this small duplication is acceptable given that it looks minor.

2024-07-04 23:29 UTC, blmarket commented on src/legacy/timer/timer.go
> +#include "../GAME2_2.h"
Interesting. It worked me (but I experienced longer than usual compile time. Maybe it was compiled twice?)

Anyway, I can simply migrate all C code references using cxgo branch.

2024-07-04 23:52 UTC, dennwc commented on src/legacy/dialog/dialog.go
> +
Sure, no problem.

2024-07-04 23:53 UTC, dennwc commented on src/legacy/timer/timer.go
> +#include "../GAME2_2.h"
It kind of works in the sense that it compiles and runs. But it will fail in weird ways afterwards. I will always use cached C file ignoring any future updates to it. So yeah, cxgo port is preferable.

2024-07-05 00:05 UTC, dennwc commented on src/legacy/dialog/dialog.go
>  import "C"
Same for `extern` - it won't work as you except if this is a sub-package. Could you try removing any `C` imports from it? If you still need these variables, you could pass it the same way as you pass functions currently.

2024-07-05 00:05 UTC, dennwc commented on src/legacy/dialog/dialog.go
>  //export sub_44D8F0
Exports won't work here too. Better remove them all as well.

2024-07-05 00:05 UTC, dennwc commented on src/legacy/timer/timer.go
> +func Sub_486320(a1 unsafe.Pointer, a2 uint32) {
Nice! I'd suggest going one small step further.

It looks like `a1` is actually a `*Timer`. So here's what you could do.

Switch to `cxgo` branch (I usually keep a second copy of `opennox` that is always on that branch) and add your `Timer` definition to the `legacy` package. You don't need it to compile.

Then, find `sub_486320` in one of the Go files in that legacy package. Change type of `a1` to your `*Timer`. And do `cd ./src && go run ./internal/fixlegacy`.

It should rewrite this function and replace offsets with actual field accesses. You can then repeat this process for other functions, going from smaller ones to larger ones. I think you can get rid of most `unsafe` accesses here this way.

2024-07-05 00:34 UTC, blmarket commented on src/legacy/timer/timer.go
> +func Sub_486320(a1 unsafe.Pointer, a2 uint32) {
Just saw this suggestion. Let me try it.

2024-07-06 02:18 UTC, blmarket commented
Seems now it goes a bit more wilder than I thought, but just giving a try.

- Replace all C references with `instance()`

2024-07-06 02:37 UTC, blmarket commented on src/legacy/timer/timer.go
> +func Sub_486320(a1 unsafe.Pointer, a2 uint32) {
Yes it did some conversions automatically, but too much additional work jumping two branches. For me it was simply easier to convert them in-place without using cxgo branch.

Can we defer this until we migrate those funcs to member of `Timer`? Wondering we can migrate `Sub_486320` to `func (timer *Timer) SetRaw(target int)` and so on.

2024-07-06 12:26 UTC, dennwc commented on src/legacy/timer/timer.go
> +func Sub_486320(a1 unsafe.Pointer, a2 uint32) {
> but too much additional work jumping two branches

This is why I keep a separate project that is always on that branch. This way you can keep both projects open at the same time.

Sure, we can defer it for the next PR.

But I'll need to carefully check the `unsafe` code that was copied here. If at any point it takes address of anything on Go side, and convert it to `int`, that will not work properly.

2024-07-06 18:20 UTC, blmarket commented on src/legacy/timer/timer.go
> +func Sub_486320(a1 unsafe.Pointer, a2 uint32) {
If the concern is to remove use of unsafe, then how about just apply https://github.com/noxworld-dev/opennox/pull/706/commits/7bef7b80bd6508bb4a54c5c4540be0fccfe79d33 ? most of the changes are covered by unit test.

2024-07-06 20:47 UTC, dennwc commented on src/legacy/dialog/test_dialog/Dialog/C3MW224K.WAV
Where's this file coming from? Is it from Nox data? Remember, we cannot distribute any data files in the repository.

2024-07-06 20:47 UTC, dennwc commented on src/legacy/dialog/test_dialog/dialog_test.go
> +func Setup() {
```suggestion
func Setup(t testing.TB) {
```
This way you can call:
```go
t.Cleanup(handles.Release)
```
And it will automatically run this function at the end of the test.

2024-07-06 20:47 UTC, dennwc commented on src/legacy/dialog/test_dialog/dialog_test.go
> +		mgr.ReadJSON("dialog_test.json")
```suggestion
		mgr := strman.New()
		if err := mgr.ReadJSON("dialog_test.json"); err != nil {
			t.Fatal(err)
		}
```

2024-07-06 20:47 UTC, dennwc commented on src/legacy/dialog/test_dialog/dialog_test.go
> +		return mgr
Looks like you are reading the file each time the function is called instead of doing it once. Maybe worth moving this code into `Setup` and just return the variable here?

2024-07-06 20:47 UTC, dennwc commented on src/legacy/dialog/test_dialog/test_env.go
> +import "C"
Hmm, I wonder why do you need all of these still. You do not expect it to link against the main `legacy` package, right? Why not make the variables on the Go side then?

2024-07-06 20:47 UTC, dennwc commented on src/legacy/timer/timer.go
> +func TimerInit(self *Timer, target int32) int32 {
```suggestion
func (t *Timer) Init(target int32) int32 {
```
Could make it a method, since its already split from C stuff. Same for other functions that operate on one timer or timer group.

Also note that by Go conventions we do not call the receiver variable `self` or `this` or `timerGroup`. We usually pick a short name like `t` for timer, etc.

2024-07-06 20:47 UTC, dennwc commented on src/legacy/timer/timer.go
> +func Sub_4862E0(a3 unsafe.Pointer, a4 int32) int32 {
Maybe remove this and let other packages call `TimerInit` directly?

2024-07-06 20:47 UTC, dennwc commented on src/legacy/timer/timer.go
> +	}
Notice how the code takes address from a local variable `v2`. This is dangerous! Go stack behaves differently to C stack. Go may allocate variables on the heap and then destroy them, if the pointer suddenly disappears (e.g. is cast to `int` type).

I would suggest rewriting this part. I noticed that first 4 bytes of `v2` are used for `if`, and the all 8 bytes are overwritten in the `if` body. Thus, these are two independent variables:
```suggestion
	v2 := *(*uint32)(unsafe.Add(a1, 8))
	v3 := *(*uint32)(unsafe.Add(a1, 4))
	*(*uint32)(a1) &= 0xFFFFFFFE
	if v2 == v3 {
		*(*uint64)(unsafe.Add(a1, 24)) = PlatformTicks()
	}
```

Since it already fixes most of the function body, you could easily fix the rest of unsafe in this function too.

2024-07-06 20:47 UTC, dennwc commented on src/legacy/timer/timer.go
> +	*(*uint32)(unsafe.Add(a1, 4*2)) = uint32(target) << 16
This one is tiny. Worth removing unsafe here for sure!

2024-07-06 20:47 UTC, dennwc commented on src/legacy/timer/timer.go
> +	} else {
Since `if` branch returns, you could drop `else` and lower the code.

2024-07-06 20:56 UTC, dennwc commented on src/legacy/dialog/dialog.go
> +	audioDriver        *ail.Driver // dword_5d4594_831092
I check the code of the branch, and it looks like you did an awesome job of extracting all functions that use these variables. Congrats! :tada: 

We can completely move these variables to Go side now. Just remove all references from C files (`vardefs.c` most importantly) and switch to local vars instead of pointers here.

2024-07-06 20:59 UTC, blmarket commented on src/legacy/dialog/test_dialog/Dialog/C3MW224K.WAV
oops, then I need to replace it with placeholder file.

2024-07-06 21:02 UTC, blmarket commented on src/legacy/dialog/test_dialog/test_env.go
> +import "C"
If we decide to move all the variables to Go side, sure why not.

2024-07-06 21:04 UTC, blmarket commented on src/legacy/timer/timer.go
> +func Sub_4862E0(a3 unsafe.Pointer, a4 int32) int32 {
Then we will lose traceability from the address (if someone tries to search func usage of 4862E0 in the future...)

2024-07-06 21:05 UTC, blmarket commented on src/legacy/timer/timer.go
> +	}
Simply missed during migration (haha;;)

2024-07-06 22:56 UTC, dennwc commented on src/legacy/timer/timer.go
> +func Sub_4862E0(a3 unsafe.Pointer, a4 int32) int32 {
But the `legacy` will still export it to C under the old name, right?

And if not - don't worry, all the old code is still in Git. Could be found if/when needed

2024-07-07 03:12 UTC, blmarket commented on src/legacy/dialog/dialog.go
> +	audioDriver        *ail.Driver // dword_5d4594_831092
Not there yet. Still a few functions accessing those fields. For example `sub_44D960`, `sub_44D970`, `sub_44D990`.

Let's keep our scope limited to "make module testable", instead of migrate them all at once.

2024-07-07 21:12 UTC, dennwc reviewed
OK, lets keep it shorter then. Only two things remain: remove C vars from tests and omit `&` when calling methods in the timer group.

2024-07-07 21:12 UTC, dennwc commented on src/legacy/dialog/test_dialog/test_env.go
> +import "C"
Since you want to wrap this PR while keeping C vars in place, maybe we could at least remove these ones for the test.

2024-07-07 21:12 UTC, dennwc commented on src/legacy/timer/timer.go
> +	(&t.Timers[2]).Update()
```suggestion
	t.Timers[0].Update()
	t.Timers[1].Update()
	t.Timers[2].Update()
```
As long as `Update` is marked as a pointer method (`func (t *Timer)`) Go will know to use the pointer here.

2024-07-09 09:48 UTC, dennwc commented on src/legacy/dialog/test_dialog/test_env.go
> +}
This still uses C imports in tests. Could you switch to `alloc.InternCString` instead? Same for `GoString`.

2024-07-11 10:24 UTC, dennwc reviewed
Looks good to me!

Would you allow me to shuffle files around a bit? Since there's no C in tests now, the tests can be in the same package as the dialog, for example.

Also, I got an idea about the `NewDialog`. I was thinking maybe I can move all the function export variables like `Sub_413890` and `GetStringManager` to a function argument of `NewDialog`. Less global state - the better.

2024-07-11 22:51 UTC, blmarket commented
> Looks good to me!
> 
> Would you allow me to shuffle files around a bit? Since there's no C in tests now, the tests can be in the same package as the dialog, for example.
> 
> Also, I got an idea about the `NewDialog`. I was thinking maybe I can move all the function export variables like `Sub_413890` and `GetStringManager` to a function argument of `NewDialog`. Less global state - the better.

Sure, I can move some by myself, but feel free to take it from here as you want. I'll try to use the same structure for the next work.

2024-07-12 21:22 UTC, dennwc commented
@blmarket Done! I moved all function to methods on `Dialog` and also removed the global state. Ready to merge, if all is good here.

2024-07-13 15:07 UTC, blmarket commented
> @blmarket Done! I moved all function to methods on `Dialog` and also removed the global state. Ready to merge, if all is good here.

Looks great to me as well! Thanks for the help! Will try to use similar structure for the future works.
Passed all my manual in-game tests.

2024-07-13 22:51 UTC, dennwc commented
@blmarket I had to squash all the commits, unfortunately. Initially I wanted to only group them (e.g. squash minor fixes only), but that Nox data file was in the middle of the commit log.

2024-07-13 22:51 UTC, merged